### ISSUE TITLE
./configure 실행시 syntax error 발생

### ISSUE THREAD

**Issue by ChunGilLee** [libhangul/ibus-hangul#100]
아래 커밋버전(아마 가장 마지막 master branch version)을 클론 하여 configure를 실행하니 
문법 에러가 발생했습니다.
---------------------

commit 25114a520211408fc9e24b826bfd4fadfdfe2612

아래는 에러 내용입니다.
---------------------
...
...
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
./configure: line 19040: syntax error near unexpected token `IBUS,'
./configure: line 19040: `PKG_CHECK_MODULES(IBUS,'

다음은 제 시스템 정보 입니다.
------------------------------------------------------
$ uname -a
Linux highvolt-notebook 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 18.04.3 LTS \n \l
$ autoconf --version
autoconf (GNU Autoconf) 2.69
$ aclocal --version
aclocal (GNU automake) 1.15.1
$ autoreconf --version
autoreconf (GNU Autoconf) 2.69

**Comment by changwoo** [comment]
그런 에러는 PKG_CHECK_MODULES 매크로가 포함이 안 된 건데요. 해당 시스템에 pkg-config 설치가 안 됐거나, 아니면 다른 이유로 안 맞아서 매크로 위치를 못 찾은 건데 ibus-hangul 소스와는 무관합니다.

**Comment by choehwanjin** [comment]
changwoo님이 말씀하신 대로 pkg-config를 설치하고 다시 configure를 실행해 보시기 바랍니다.

```
sudo apt install pkg-config
```

**Comment by choehwanjin** [comment]
추가 의견이 없으므로 이 이슈는 문제 없는 것으로 보고 닫도록 하겠습니다.
