### ISSUE TITLE
Visual Studio Code에서 한글 "감" 입력시 "가ㅁ"으로 표시되는 문제

### ISSUE THREAD

**Issue by nin187** [libhangul/ibus-hangul#108]
라즈베리파이 4 Ubuntu 20.10 ARM64이구요. VSCode는 1.53.2 ARM64 버전입니다
"감"이라는 글자가 "가ㅁ"으로 표시되네요.
저 상태로 한글자로 인식해서인지 지우면 "가ㅁ" 전체가 지워집니다.

몇 가지 테스트 해보니, 가+받침은 죄다 저런식으로 표시되네요.

**Comment by soshimee** [comment]
폰트문제입니다 폰트바꾸시면 되요
Droid Sans부분이 문제인것같더라고요

**Comment by choehwanjin** [comment]
그렇다면 입력기의 문제가 아닌 것 같으므로 이 이슈는 닫도록 하겠습니다.
