### ISSUE TITLE
The execution order of committing text and adding space using spacebar can sometimes appear to be jumbled in GNOME 45 wayland

### ISSUE THREAD

**Issue by FiestaLake** [libhangul/ibus-hangul#118]
Which distribution and version?:
Arch Linux, Fedora Linux 39 beta

Which desktop environment and version?:
GNOME 45.0
(Have been working fine since GNOME 40~44)

Which session type?:
Wayland
(Working fine in X11)

Which application and version?:
GTK4 applications (kgx, gnome-text-editor, etc...)
GTK3 applications (gnome-terminal, gedit, etc...)
Haven't tested on GTK2 applications
Works flawlessly on QT applications.

IBus version?:
Both IBus 1.5.28 and latest master

Ibus-hangul version?:
Ibus-hangul 1.5.4

Issue description:
On race situations, the execution order of committing text and adding space using spacebar appears to be jumbled.

Steps to reproduce:

    1. Type some random sentences that have spaces in Korean fast enough.
    -> For my case, I typed:'동해 물과 백두산이 마르고 닳도록'
    2. The text shown should be same as what I typed,
       but you'll get something like "동해 물과 백두산이 마르 고닳도록'
    
Can you reproduce your problem when you restart ibus-daemon? (yes / no):
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):
yes

**Comment by FiestaLake** [comment]
https://github.com/fujiwarat/ibus/commit/f176569cf774f87b23270257da68249dcda837c9
https://github.com/ibus/ibus/issues/2570#issuecomment-1767902411
It will be fixed on the mainstream ibus side. Will close the issue once this fix is merged to the main branch.

**Comment by FiestaLake** [comment]
Although the above fix does reduce the occurrence of the bug, it still occurs when we type texts really fast.

**Comment by JeffGolub** [comment]
저 도동일 한문제 를가지고 있습니다. arch 6.5.8, gnome 45.0, wayland, ibus 1.5.28이며 최근 업데이 트후 문제가 발생하였습니다.

**Comment by fujiwarat** [comment]
If you mean GNOME Wayland , i.e. GTK_IM_MODULE=wayland only, it would be a gnome-shell or mutter issue.
If you mean GNOME Xorg, i.e. GTK_IM_MODULE=ibus only, it would be an ibus issue.

**Comment by puelp** [comment]
This bug is still present in Fedora 39 Workstation with all the latest updates applied:
GNOME 45.1 Wayland
ibus 1.5.29~rc2
ibus-hangul 1.5.5

Judging by the lack of activity on this page, there seems to be no urgency in getting this bug fixed, and no solution in sight.

If I recall correctly, the last time that a bug like this happened, the bug remained unfixed for months/years.

What can end-users do to make sure that doesn't happen again? How can we help troubleshoot and help fix this bug?

**Comment by fujiwarat** [comment]
I sometimes can reproduce this issue.
The described test case is:
ehd go anf rhk qor en tks dl ak fm rh ekfg eh fhr

I'd suggest to report the issue to gnome-shell.

CC'ing @epico

**Comment by mike-fabian** [comment]
The same issue also occurs when using ibus-m17n: https://github.com/ibus/ibus-m17n/issues/72
I think https://github.com/ibus/ibus-m17n/issues/72#issuecomment-1822281847 shows that  this is not a problem caused by the input method but it must be a Gnome or Mutter problem.

**Comment by jimnong** [comment]
gnome 44까지는 정상이었기 때문에, ibus-hangul에 이슈 보고는 적절치 않아 보입니다.

GNOME 측에 issue report 했고, mutter 문제로 방향이 잡힌 것 같습니다.

https://gitlab.gnome.org/GNOME/mutter/-/issues/3216
위 링크에서 소통하는 속도가 더딜 경우, 적극적으로 참여해 주시길 바랍니다.

**Comment by fujiwarat** [comment]
@jimnong I think your issue is duplicated of https://gitlab.gnome.org/GNOME/mutter/-/issues/3090

**Comment by FiestaLake** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3536 has been merged to main as a fix for the issue. Closing the issue.
