### ISSUE TITLE
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

### ISSUE THREAD

**Issue by changwoo** [libhangul/ibus-hangul#29]
동작은 같은데 무슨 메시지가 표시되네요.

$ ibus-setup-hangul 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

ibus-anthy 코드 보면 뭔가 복잡한 처리가 되어 있는데 왜 이렇게 하는지는 아직 모르겠습니다..

https://github.com/ibus/ibus-anthy/blob/master/setup/python3/main.py#L87

**Comment by choehwanjin** [comment]
8fa5631 에서 수정하였습니다.
