### ISSUE TITLE
Release a new version of ibus-hangul

### ISSUE THREAD

**Issue by fujiwarat** [libhangul/ibus-hangul#52]
I think the git master uses ibus_engine_forward_key_event() but
ibus-hangul 1.5.0 does not have that implementation.
Recently Peng Wu fixed ForwardKeyEvent issue in Qt5;
https://codereview.qt-project.org/#/c/212179/

**Comment by fujiwarat** [comment]
CC'ing @epico

**Comment by juhp** [comment]
Ping? :)

**Comment by changwoo** [comment]
> Recently Peng Wu fixed ForwardKeyEvent issue in Qt5;
> https://codereview.qt-project.org/#/c/212179/

I found this patch has been applied in Debian but still ForwardKeyEvent doesn't seem to work.

**Comment by fujiwarat** [comment]
@changwoo You need to have https://github.com/choehwanjin/ibus-hangul/commit/5f7813ea5b303d5f7b43a9fe3a111c706c32a876

**Comment by changwoo** [comment]
@fujiwarat I already have the ibus-hangul git version packaged in Debian. In Qt apps, nothing happens when I press non-IM keys, as if there's no ForwardKeyEvent implementation.

**Comment by changwoo** [comment]
> @fujiwarat I already have the ibus-hangul git version packaged in Debian. In Qt apps, nothing happens when I press non-IM keys, as if there's no ForwardKeyEvent implementation.

My mistake. It needs from Qt 5.11 from Debian experimental, released May 22.

**Comment by epico** [comment]
Any progress? :)

**Comment by choehwanjin** [comment]
Okay, I will release a new version soon.

**Comment by changwoo** [comment]
I finally tried Qt apps, virtualbox and telegram-desktop, under Qt 5.11, I successfully got space when I press space key. Yeay! But I got full-width characters "（ｒｑｔｓ" when I pressed backspace and arrow keys. I'm still finding what is wrong.

**Comment by changwoo** [comment]
> full-width characters "（ｒｑｔｓ" when I pressed backspace and arrow keys.

@fujiwarat  I think the Qt ForwardKeyEvent patch needs conversion between ibus key codes and qt key codes. ASCII-printable keycodes are the same but other special key codes seems to be different.

**Comment by choehwanjin** [comment]
I've released a new version 1.5.1.
https://github.com/libhangul/ibus-hangul/releases/tag/1.5.1
