### ISSUE TITLE
Broken with new GNOME versions

### ISSUE THREAD

**Issue by pothos** [libhangul/ibus-hangul#55]
Running Debian sid typing does commit too early unless I switch to word-unit composition. But anyway space, enter, backspace and arrow keys are broken as well.

**Comment by timothykim** [comment]
I'm running into the similar commit issue. However, my space, enter, backspace and arrow keys are working as expected.

저도 비슷한 문제가 있습니다.  한타를 할 때 첫 글짜는 commit이 예상대로 되나 그 이후에서 자모따로 commit이 됩니다. 

사양은 다음과 같습니다:

- Fedora 28
- GNOME Shell 3.28.1
- ibus 1.5.18
- ibus-hangul 1.5.0

위분께서 올리신 것처럼 단어 단위 commit을 하면 문제가 없습니다.

**Comment by timothykim** [comment]
위 문제를 영상으로 담아 봤습니다. 도움이 되었스면 합니다.

https://www.youtube.com/watch?v=9u1H86SJsfU

**Comment by changwoo** [comment]
이 문제는 ibus-hangul과 직접 관계없어 보이고 wayland에서 망가진 겁니다. xorg 세션은 멀쩡합니다.

**Comment by changwoo** [comment]
이 문제입니다. 한글 입력은 commit과 동시에 preedit 상태를 업데이트하는데 mutter 쪽에서 커밋 후에 preedit 상태를 리셋해 버리게 작성되어 있습니다.

https://gitlab.gnome.org/GNOME/mutter/issues/152

**Comment by changwoo** [comment]
머지되었습니다. https://gitlab.gnome.org/GNOME/mutter/merge_requests/108  

이 이슈는 닫아도 됩니다.

쉽게 피해가는 방법은 GTK_IM_MODULE=ibus 환경 변수를 넣는 것입니다. 데비안이나 데비안 파생 배포판이면 im-config를 사용해서 설정할 수 있고요.

**Comment by choehwanjin** [comment]
mutter 쪽에서 수정되었으니 이 이슈는 닫겠습니다.
