### ISSUE TITLE
1.5.1 - libhangul 최소 버전 조정 필요

### ISSUE THREAD

**Issue by changwoo** [libhangul/ibus-hangul#65]
hangul_init(), hangul_fini() 때문에 1.5.1은 libhangul 0.1.0 릴리스 버전에서는 빌드되지 않습니다. libhangul 릴리스 뒤에 libhangul 최소 버전을 바꿔서 지정해야 할 것 같습니다.

**Comment by choehwanjin** [comment]
1.5.1에서는 아직 hangul_init()/hangul_fini()를 적용하지 않았습니다.
혹시  다른 문제가 아닌지 확인 부탁드립니다.

**Comment by changwoo** [comment]
제가 잘못 알았습니다.  감사합니다.
