### ISSUE TITLE
Migrate from Intltool to Gettext

### ISSUE THREAD

**Issue by t-chaik** [libhangul/ibus-hangul#80]
Recent gettext versions can extract and merge back strings from and to various file formats, not need for deprecated intltool any more. Migrating modules to gettext is a [GNOME Goal](https://wiki.gnome.org/Initiatives/GnomeGoals/GettextMigration).

ibus itself has [already been ported](https://github.com/ibus/ibus/commit/a6710817b3d29d6a522f108f96ffe64d2f5367fe).

**Comment by choehwanjin** [comment]
Thank you for your patch.
I will check.

**Comment by t-chaik** [comment]
@choehwanjin: Thanks for reviewing this! Any idea when you'll cut a new version of `ibus-hangul`? Would be awesome to have a stable release free of these two deprecated dependencies (`gnome-common` and `intltool`).
