### ISSUE TITLE
tarball에 (불필요한?) po/POTFILES.skip 파일 누락

### ISSUE THREAD

**Issue by changwoo** [libhangul/ibus-hangul#89]
1.5.2 릴리스 tarball을 보면 git에 들어 있는 po/POTFILES.skip 파일이 들어 있지 않습니다. 생성된 po/Makefile.in.in 파일에서 POTFILES.skip 파일을 포함하지 않는 것으로 보입니다.

#80 관련되서 추가된 것 같은데, 오히려 이 파일은 intltool에서만 쓰는 파일이라서 의미 없는 파일이 추가된 것 같은데 확실히는 모르겠네요. 불필요하면 삭제하면 될 것 같습니다.

**Comment by choehwanjin** [comment]
고맙습니다.
확인해보겠습니다.
