### ISSUE TITLE
1.5.2 시작되자 마자 끝남

### ISSUE THREAD

**Issue by changwoo** [libhangul/ibus-hangul#90]
https://github.com/libhangul/ibus-hangul/blob/e6414481715b6db39382c9348abd8df88d40acc3/src/engine.c#L327

시작되자 마자 끝나서 동작하지 않는데 위 부분이 문제인 것 같습니다.

**Comment by choehwanjin** [comment]
이거 실수 했네요.
테스트로 넣은 코드를 안지우고 커밋했나 봅니다.
수정하겠습니다.

**Comment by chrisleekr** [comment]
Arch 리눅스를 사용하시는 분들 중 위 코드로 인해 한글 입력이 갑자기 안되시는 분들은 다음과 같이 하시면 다시 사용하실 수 있으실 거에요. 도움이 될까해서 코멘트 남겨놓습니다.

아직 PKGBUILD에 1.5.3으로 업데이트가 되질 않아서 나타나는 현상입니다.
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ibus-hangul

```
$ cd /tmp
$ yay -G ibus-hangul
$ cd ibus-hangul
$ vim PKGBUILD
```

여기서 `pkgver=1.5.2`를 `pkgver=1.5.3`로 수정합니다.

```
$makepkg -si --skipchecksums
```

설치하신뒤에 Reboot 하시면 됩니다.

**Comment by choehwanjin** [comment]
1.5.3을 릴리스 하였으니 이 이슈는 닫겠습니다.
