### ISSUE TITLE
ibus-hangul not working with hangul toggle keys

### ISSUE THREAD

**Issue by wreckdump** [libhangul/ibus-hangul#92]
I've been using ibus-hangul for few years now and after a system update, it suddenly stopped working. ibus menu do popup when I press the keyboard shortcuts. But even after pressing toggle key for hangul the input language does not change.

I do get an warning message saying 

```
/usr/share/ibus-hangul/setup/main.py:298: DeprecationWarning: bind_textdomain_codeset() is deprecated
  gettext.bind_textdomain_codeset(config.gettext_package, "UTF-8")
```

but it still let's me change the toggles keys, but it wouldn't work...

Help please..?

Thank you.

**Comment by tttuuu888** [comment]
안녕하세요 저 역시 같은 증상을 경험하였습니다.
arch linux 이고 며칠전 업데이트 후 한글 토글이 되지 않습니다.
ibus-daemon -v 후 한글 토글 시 로그를 아래와 같이 추가합니다.

```
(ibus-ui-gtk3:10281): IBUS-WARNING **: 02:49:13.548: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:10281): IBUS-WARNING **: 02:49:28.585: ibus_bus_call_sync: org.freedesktop.IBus.SetGlobalEngine: GDBus.Error:org.freedesktop.DBus.Error.Failed: Set global engine failed: Timeout was reached

(ibus-ui-gtk3:10281): IBUS-WARNING **: 02:49:28.585: panel.vala:811: Switch engine to hangul failed.

```

감사합니다.

**Comment by choehwanjin** [comment]
혹시 1.5.2 버전을 사용하는 것은 아닌지 확인 부탁드립니다.
1.5.2 버전에 버그가 있습니다. 아래 이슈를 확인해보시기 바랍니다.
https://github.com/libhangul/ibus-hangul/issues/90

**Comment by wreckdump** [comment]
감사합니다. 1.5.1로 다운그레이드 했었는데 1.5.3 버젼으로 업데이트 하니 작동이 잘 되네요. 그런데 혹시 파이어폭스 버젼 71.0 에서 탭 상의 한글이 다 뭉게져서 표시되는 현상도 ibus-hangul 관련 문제일까요? 사진 첨부합니다.

[https://ibb.co/vx8P62j](url) 

또, 파이어폭시 주소창에 한글 입력시에도 한글들이 뭉게져서 표현되는 현상이 일어나는 반면에 인터넷 창 상에서의 검색어 입력시엔 이런 현상이 없네요...

**Comment by tttuuu888** [comment]
@choehwanjin 1.5.3.1 업데이트 후 정상동작 확인하였습니다. 감사합니다.

**Comment by choehwanjin** [comment]
문제가 해결된 것으로 알고 닫겠습니다.

**Comment by wreckdump** [comment]
마지막에 언급한 문제 해결했습니다. Arch Linux에서 한자 패키지 wqy-microhei 를 동시에 사용 중이었는데 이 패키지 제거하니까 문제 해결됐습니다.

감사합니다.
