### ISSUE TITLE
특정 앱이 focus 된 상태에서 ibus toggle key 비활성화

### ISSUE THREAD

**Issue by hackmalife** [libhangul/ibus-hangul#94]
특정 앱이 focus 된 상태에서는 hangul toggle 단축키가 안먹히도록 할수 있을까요??

**Comment by choehwanjin** [comment]
한글 엔진에서는 각 클라이언트를 구분할 수 없어서 클라이언트 별 동작이 어렵습니다.

구체적으로 어떤 것을 원하시는 건가요?

**Comment by hackmalife** [comment]
네 다른 방법을 찾아보겠습니다~ 감사합니다~
