### ISSUE TITLE
Alt_R and Ctrl_R - allow their keycodes to not be remapped

### ISSUE THREAD

**Issue by J-J-Chiarella** [libhangul/ibus-hangul#95]
I am writing this in English, but I can translate anything to Korean if need be. Feel free to comment in Korean or English.

IBus can interpret a modifier key as an event trigger in combination with another key (e.g., Shift and Space) or it can detect a modifier key as an event trigger in and of itself, with discrimination as to left and right (e.g., Alt_R all by itself, not with another key, and not Alt_L).

Given this, it is a huge inconvenience that the Right Alt key gets mapped to Hangul/English automatically in ibus-hangul no matter what. If ibus can detect and register a lone Right Alt for the Hangul/English toggle key or a lone Right Control for the Hanja commit key, then there is no need to re-map the keycode for a right alt press or to re-map the keycode for a right control press.

The current set-up makes it impossible to use the right alt and the right control keys. Using only the Control on the left for commands in the terminal or a word processor is extremely inconvenient. Using only the Alt on the left is similarly inconvenient. We have Shift keys on both the left and the right for a reason. The same should be true for the Control and Alt keys.

I can get ibus to do what I want if I fiddle with XKB settings (I use XFCE).

The only downside to keeping Right Alt as Right Alt and using it to toggle the hangul mode and keeping right control as right control and using it to trigger hanja commits, is that tapping Right Alt will only toggle hangul mode and not make an auto-hide menu bar appear. I can live without that. The hangul/English toggle works exactly as expected. Tap Right Alt once to toggle Hangul/English mode. If you hold Right Alt and hit the left arrow button, then the browser goes back one page. If you tap the right control, then the hangul syllable can be converted into a hanja. If you hold the right control and hit the "V" key, then you get a paste function and the hanja menu does not appear.

This is much better for my workflow, and I imagine for others as well. The unfortunate thing is that after some time, ibus will re-assert itself as the grand master of input and typing, which means that Right Alt (USB 230) will be mapped as Hangul/English dedicated key (USB144) and Right Control (USB 228) will be mapped as Hanja key (USB 145).

I would like to request disabling the key-mapping and to leave USB 230 as USB 230 and USB 228 as USB 228.

If for some reason to do with Wine and running Windows programs that bypass ibus and rely on the emulation of USB 144 and of USB 145, then I would like to ask that there is a checkbox to have the key re-mapping be optional.

I use copy-cut-paste often and I am a touch typist in Latin (US English layout) and in Hangul. I sorely miss the ability to use right control and right alt.

Thank you for your time

**Comment by changwoo** [comment]
This remapping is not exactly by ibus or ibus-hangul. XKB settings does it. (Actually I'm the one who wrote the Korean keyboard part in xkeyboard-config.)

You can opt-out this mapping as you wish. Choose "kr" layout instead of "kr(kr104)" "104-key compatible" (kr(kr104)) to avoid this remapping. Be sure to use "System layout" in the ibus settings.

I believe remapping those keys is the reasonable default, as many Korean keyboards use Alt_R as 한/영 and Ctrl_R as 한자.

**Comment by J-J-Chiarella** [comment]
Thank you for your suggestion, but this workaround creates worse (?) problems.

Using the force "system layout" makes every other ibus engine not work, like French with its accented characters or rearranged qwerty. This happens to any other script that isn't "complex" like hangul or Japanese kana. Every other ibus option becomes unusable. Forcing a fallback onto XKB means that I have to assign a shortcut to change XKB layouts, which are often not as good as the IBus equivalent.

Most significantly, I plan to soon switch to Sway, which is Wayland-only. Does this cause problems with an XKB fallback?

> I believe remapping those keys is the reasonable default, as many Korean keyboards use Alt_R as 한/영 and Ctrl_R as 한자.

Please excuse my ignorance here, but is there any reason to keep doing this? Alt_R is already enabled by default as an option for Hangul toggling in ibus-hangul and Ctrl_R is already enabled by default as a Hanja commit key.

Remapping Alt_R to a different virtual key seems to provide no benefit. Unlike fcitx, ibus can interpret Alt_R by itself or Ctrl_R by itself as a trigger. I do not see the technical reason to keep it this way.

I also know that a work computer I used years ago at a high school operated exactly as I described, where Alt_R worked as expected when held down (Alt + Tab and so forth) and toggled Hangul/English when tapped. It was Windows XP or Windows 7. Maybe that's not the default anymore -- I haven't run Windows at home or been forced to use Windows for several years, but it was how some Windows IME did function on Korean computers in Korea (South).

**Comment by J-J-Chiarella** [comment]
One thing I encountered. ibus-hangul can handle Alt_R on its own, but the general ibus cannot.

I figure there could be cases where someone wants to set ibus-hangul to always run as hangul mode and to use Alt_R as a trigger for switching between ibus-libpinyin, ibus-anthy, and others, which would require its remapping to a "proper" non-modifier key.

I have to think about whether I want to (1) sacrifice the usage of the right side Alt key as Alt and use ibus all the way, or (2) juggle ibus and xkb switches. This would mean using ibus for hangul and pinyin/hanzi, but switching to ibus-english and then using an XKB layout switch key to go into French. This means that a few scripts are in ibus, then others are in XKB and require me to go to an ibus layout that is "plain" like ibus-english.

I still think an option within ibus-hangul to not re-map or to re-map the key presses for Alt_R and Ctrl_R could be useful.

Anyhow, this is all food for thought. Thank you for the work put into this. Multi-lingual typing is so much further than it was 15 years ago.

**Comment by J-J-Chiarella** [comment]
I think I understand better.

> This remapping is not exactly by ibus or ibus-hangul. XKB settings does it. (Actually I'm the one who wrote the Korean keyboard part in xkeyboard-config.)

ibus exists so as to provide complex input and to easily switch layouts via xkb. Most of the ibus options are just presets (with an icon of a generic keyboard), which is why the option to use system layout (xkb) in ibus-preferences overrides that. They do not re-map keycodes per se; they change the character that the X system interprets.

In order to get what I want, I will need to sacrifice the centralization of ibus and switch out of anthy or pinyin or whatever and then use a different shortcut to switch XKB layouts (French, Arabic, Dvorak, or a custom layout). I use accented characters and simplified hanzi rarely enough that this is okay. Still, it would be nice to modify the XKB layouts through the ibus-preferences interface. Have a good day.

**Comment by changwoo** [comment]
> > I believe remapping those keys is the reasonable default, as many Korean keyboards use Alt_R as 한/영 and Ctrl_R as 한자.
> 
> Please excuse my ignorance here, but is there any reason to keep doing this? Alt_R is already enabled by default as an option for Hangul toggling in ibus-hangul and Ctrl_R is already enabled by default as a Hanja commit key.

AFAIK, Alt_R is not the default, but Hangul(한/영) key is the default. That's why remapping is required in such "104-key compatible" keyboards.

> Remapping Alt_R to a different virtual key seems to provide no benefit. Unlike fcitx, ibus can interpret Alt_R by itself or Ctrl_R by itself as a trigger. I do not see the technical reason to keep it this way.

Using Alt_R as the Hangul key without remapping breaks many apps. It's because Alt_R is a modifier key. Many apps break in that way. When you press Alt_R in Firefox, it will open your (hidden) menu bar.

> I also know that a work computer I used years ago at a high school operated exactly as I described, where Alt_R worked as expected when held down (Alt + Tab and so forth) and toggled Hangul/English when tapped. It was Windows XP or Windows 7. Maybe that's not the default anymore -- I haven't run Windows at home or been forced to use Windows for several years, but it was how some Windows IME did function on Korean computers in Korea (South).

ibus or ibus-hangul can't implement this. Apps like Firefox and desktop need to be modified to use the Hangul key as your suggestion.

And this breaks how users have used the Hangul key for decades. Hangul/Hanja keys were implemented as press-only key since AT/PS2 keyboard era. Users expect these key work on press, not on release.

**Comment by J-J-Chiarella** [comment]
> ibus or ibus-hangul can't implement this. Apps like Firefox and desktop need to be modified to use the Hangul key as your suggestion.

Hmm... I guess so. Sometimes when I monkey around with it, it behaves as I suggest and at others times it behaves like you are saying. My ideal may have been some specially modified XP computer and somebody tweaked registry or who knows what. Obviously, back then, Firefox did not have an auto-hide menu bar. But just tapping the right Alt did not trigger the shortcut hints to appear (the "F" of "File" gets underlined, and so forth).

> ibus or ibus-hangul can't implement this. Apps like Firefox and desktop need to be modified to use the Hangul key as your suggestion.

That makes sense to make the Hangul toggle to be a regular press then. There may be many users to type so fast that they hit the right alt key (or dedicated Hangul toggle key, rare as it is these days) and then hit a regular key at nearly the same time and may hit Alt+F to open the file menu instead of getting "ㄹ" to appear.

> ibus or ibus-hangul can't implement this. Apps like Firefox and desktop need to be modified to use the Hangul key as your suggestion.

For a couple of years, the Ubuntu default has been for both the dedicated Hangul key and for Alt_R to toggle Hangul mode. Presumably this is in case the XKB remapping fails. This way, a user is still able to toggle Hangul mode without having to add new shortcuts to the ibus-hangul preferences.

This has been educational for me, thank you. Lo and behold, there is always some legacy reason or some habitual quirk I overlooked. (In this case, users expecting Hangul toggle to happen immediately and then the key to essentially quit so that it does not also activate a menu shortcut when pressed simultaneously with F or D or E or O.)

**Comment by changwoo** [comment]
> For a couple of years, the Ubuntu default has been for both the dedicated Hangul key and for Alt_R to toggle Hangul mode. Presumably this is in case the XKB remapping fails. This way, a user is still able to toggle Hangul mode without having to add new shortcuts to the ibus-hangul preferences.

Could you tell us which settings has Alt_R for Hangul toggle? Alt_R is not the default in ibus/ibus-hangul and it's seriously broken if Ubuntu customized it as the default. Alt_R should not be used for Hangul when you change the XKB layout.

**Comment by J-J-Chiarella** [comment]
I have been running my installation for a few years. I'm probably wrong on the the default front. It was probably a setting saved in /home from some non-LTS release. I cannot remember exactly when, but there was some bug report on launchpad for ibus-hangul related to Alt_R not getting captured correctly and the bug getting some workaround in an update or with the next version of Ubuntu. It could be a matter of upgrading on top of upgrading messing with the settings or something. There was some workaround I did. I found the bug report through a Google search. Maybe it was an ibus problem overall.

I am trying to find it that bug in vain. Maybe there was some configuration that got triggered to bring up the default XKB mappings as fallbacks or something.

Maybe I was testing toggle shortcuts in the preferences and I hit Alt_R and the system was not automatically converting that to "Hangul" key. I don't know how I could have manually changed it on purpose. I only ever experimented with the XFCE keyboard settings (XKB) a few days ago. If I were to try to change it through the ibus-preferences GUI, then the GUI would just tell me that I hit the "Hangul" key and not "Alt_R."

Ubuntu has bigger issues anyhow. I will probably switch to Debian completely next year and rely on FlatPak for up-to-date programs like Firefox or VLC. I am getting sick of ibus completely not working with Qt or something else every other release and then finding a launchpad bug report with workarounds that don't work and then a message saying a patch will be applied at the next release in 6 months. The testing and Q&A could be better.

I was disappointed about the loss of the right Alt and Control when I first started typing in Korean in 2008. I learned to live with it by getting into the nasty habit of stretching my left hand to do gymnastics like Ctrl+Shift+T with one hand. I wanted to finally type properly again (a few days ago) and that's when I first fiddled with everything.

It is probably best to forget the whole matter. I made some erroneous assumptions. I think I will just live with a mix of ibus for complex IME and using one shortcut and then using a different shortcut to switch between different XKB layouts. I will miss ibus's graphical pop-up, but oh well. For ergonomic reasons, I should remap a couple other modifier keys as well.

**Comment by J-J-Chiarella** [comment]
I know it's way past the fact, but I found some verification I was not crazy:

[Fujiwara's blog May 28, 2012](https://desktopi18n.wordpress.com/2012/05/28/customize-shortcut-keys-for-ibus-1-5)

The timeline fits my thinking that way back then some distributions or implementations or ibus or ibus-hangul did use both Hangul and Alt_R as Hangul triggers and the key remapping operated differently. I am not trying to re-open the question of what I prefer. I just wanted to establish (to myself) that I wasn't crazy.
