### ISSUE TITLE
GLib-GIO-ERROR from 1.5.1

### ISSUE THREAD

**Issue by whjeon329** [libhangul/ibus-hangul#97]
Hello, 
I'm using Gnome DE, installed both 'ibus' & 'ibus-hangul'.

[1]
`Settings > Region & Language > (under 'Input Sources') '+' click > (added) Korean (Hangul)`

If I click preference button, which is located on the 3rd from right, nothing happens.
So I launched 'ibus-setup-hangul' from terminal and then error below appeared.

`(ibus-setup-hangul:7018): GLib-GIO-ERROR **: 09:59:56.627: Settings schema 'org.freedesktop.ibus.engine.hangul' is not installed`

[2]
After that, I tried to add 'ibus-hangul' manually, from 'ibus-setup' launcher.
ibus-preference > (tab) Input Method > 'Add' > (added) Korean (Hangul) > and the 'Preference' button grayed out, and can't click.

How can I resolve this issue? If you need any more information, I'll provide it.
Thanks for your hard work! 

P.S. Sorry for the bad English but I can't type Korean by the reason you see above.

OS: Funtoo 1.4
DE: Gnome
ibus version: 1.5.20
ibus-hangul version: 1.5.1

**Comment by choehwanjin** [comment]
GSettings schema 파일이 제대로 설치가 안된 것 같네요.

/usr/share/glib-2.0/schemas/org.freedesktop.ibus.engine.hangul.gschema.xml

파일이 있는지 확인해보는 것이 좋겠습니다.

**Comment by whjeon329** [comment]
The file itself exists under '/usr/share/glib-2.0/schemas/org.freedesktop.ibus.engine.hangul.gschema.xml'.
For the comparison purpose, I'll attach that file.

I'll try recompile 

P.S. Ok, attach failed. github don't support xml type. I didn't know that. Below is the copy of that file.
===
```
$ cat /usr/share/glib-2.0/schemas/org.freedesktop.ibus.engine.hangul.gschema.xml 
<?xml version="1.0" encoding="UTF-8"?>
<schemalist>
  <schema path="/org/freedesktop/ibus/engine/hangul/"
          id="org.freedesktop.ibus.engine.hangul">
    <key name="hangul-keyboard" type="s">
      <default>'2'</default>
      <summary>Hangul keyboard</summary>
      <description></description>
    </key>
    <key name="initial-input-mode" type="s">
      <default>'latin'</default>
      <summary>Initial input mode</summary>
      <description></description>
    </key>
    <key name="word-commit" type="b">
      <default>false</default>
      <summary>Word commit</summary>
      <description></description>
    </key>
    <key name="auto-reorder" type="b">
      <default>true</default>
      <summary>Auto reorder</summary>
      <description></description>
    </key>
    <key name="switch-keys" type="s">
      <default>'Hangul,Shift+space'</default>
      <summary>Switch keys</summary>
      <description></description>
    </key>
    <key name="hanja-keys" type="s">
      <default>'Hangul_Hanja,F9'</default>
      <summary>Hanja keys</summary>
      <description></description>
    </key>
    <key name="on-keys" type="s">
      <default>''</default>
      <summary>On keys</summary>
      <description></description>
    </key>
    <key name="off-keys" type="s">
      <default>''</default>
      <summary>Off keys</summary>
      <description></description>
    </key>
    <key name="disable-latin-mode" type="b">
      <default>false</default>
      <summary>Disable Latin mode</summary>
      <description></description>
    </key>
    <key name="use-event-forwarding" type="b">
      <default>true</default>
      <summary>Enable event forwarding workaround</summary>
      <description></description>
    </key>
  </schema>
</schemalist>
```

**Comment by whjeon329** [comment]
펀투 패키지 기준 1.5.0-r1으로 다운그레이드하니 정상 작동합니다.
감사합니다!
